WebApplication/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace WebApplication.Controllers
{
	[Authorize]
	public class RoleController : Controller
    {
		ApplicationDbContext context;

		public RoleController()
		{
			context = new ApplicationDbContext();
		}

		/// <summary>
		/// Get All Roles
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{

			if (User.Identity.IsAuthenticated)
			{


				if (!isAdminUser())
				{
					return RedirectToAction("Index", "Home");
				}
			}
			else
			{
				return RedirectToAction("Index", "Home");
			}

			var Roles = context.Roles.ToList();
			return View(Roles);

		}
		public Boolean isAdminUser()
		{
			if (User.Identity.IsAuthenticated)
			{
				var user = User.Identity;
				var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
				var s = UserManager.GetRoles(user.GetUserId());
				if (s[0].ToString() == "Admin")
				{
					return true;
				}
				else
				{
					return false;
				}
			}
			return false;
		}
		/// <summary>
		/// Create  a New role
		/// </summary>
		/// <returns></returns>
		public ActionResult Create()
		{
			if (User.Identity.IsAuthenticated)
			{


				if (!isAdminUser())
				{
					return RedirectToAction("Index", "Home");
				}
			}
			else
			{
				return RedirectToAction("Index", "Home");
			}

			var Role = new IdentityRole();
			return View(Role);
		}

		/// <summary>
		/// Create a New Role
		/// </summary>
		/// <param name="Role"></param>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Create(IdentityRole Role)
		{
			if (User.Identity.IsAuthenticated)
			{
				if (!isAdminUser())
				{
					return RedirectToAction("Index", "Home");
				}
			}
			else
			{
				return RedirectToAction("Index", "Home");
			}

			context.Roles.Add(Role);
			context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

WebApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using WebApplication.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using System.Data.Entity;

namespace WebApplication.Controllers
{
	//[Authorize]
	public class UsersController : Controller
    {

       

        // GET: Users
        public Boolean isAdminUser()
		{
			if (User.Identity.IsAuthenticated)
			{
				var user = User.Identity;
				ApplicationDbContext context = new ApplicationDbContext();
				var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
				var s = UserManager.GetRoles(user.GetUserId());
				if (s[0].ToString() == "Admin")
				{
					return true;
				}
				else
				{
					return false;
				}
			}
			return false;
		}
		public ActionResult Index1()
		{
			if (User.Identity.IsAuthenticated)
			{
				var user = User.Identity;
				ViewBag.Name = user.Name;
				//	ApplicationDbContext context = new ApplicationDbContext();
				//	var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

				//var s=	UserManager.GetRoles(user.GetUserId());
				ViewBag.displayMenu = "No";

				if (isAdminUser())
				{
					ViewBag.displayMenu = "Yes";
				}
				return View();
			}
			else
			{
				ViewBag.Name = "Not Logged IN";
			}


			return View();
              }

        public ActionResult Index()
        {
            return View("Users");
        }

        public ActionResult Users_Read([DataSourceRequest] DataSourceRequest request)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            
            return Json(UserManager.Users.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


        public ActionResult Picture(string id)
        {
            if (id != null)
            {
                return base.File("../../Content/contacts/" + id + ".jpg", "image/jpeg");
            }
            else
            {
                return base.File("../../Content/contacts/" + "default-contact.png", "image/jpeg");
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> EditingPopup_Create([DataSourceRequest] DataSourceRequest request, RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {

                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };

                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));


                var adminresult =await  UserManager.CreateAsync(user, userViewModel.Password = "Admin123!@#");
                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
            }
          
            return Json(new[] { userViewModel }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> EditingPopup_Update([DataSourceRequest] DataSourceRequest request,  ApplicationUser userViewModel, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));


                var user = await UserManager.FindByIdAsync(userViewModel.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = userViewModel.Email;
                user.Email = userViewModel.Email;
                user.PhoneNumber = userViewModel.PhoneNumber;
                user.EmailConfirmed = userViewModel.EmailConfirmed;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");

          
            return Json(new[] { userViewModel }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> EditingPopup_Destroy([DataSourceRequest] DataSourceRequest request, ApplicationUser userViewModel)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));


                var user = await UserManager.FindByIdAsync(userViewModel.Id);

                if (user == null)
                {
                    return HttpNotFound();
                }

                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }

            }
            ////===================================================================================================================
            //string sX = userViewModel.GetStringWith_RecordProperties();
            ////===================================================================================================================
            //var logRecord = new WriteUsageLog();
            //logRecord.Note = "New WorkFlow Record Added - " + sX;

            //logRecord.UserLogIn = General_ActiveDirectory_Extensions.fn_sUser();
            //string IP = Request.UserHostName;
            //logRecord.ComputerName = General_functions.fn_ComputerName(IP);

            //_writeUsageLogService.Create(logRecord);
            ////===================================================================================================================

            return Json(new[] { userViewModel }.ToDataSourceResult(request, ModelState));
        }

    }
}

WebApplication/Views/Users/Index1.cshtml
@{
    ViewBag.Title = "Index";
}



@if (ViewBag.displayMenu == "Yes")
{
    <h1>Welcome Admin. Now you can create user Role.</h1>
    <h3>
        <li>@Html.ActionLink("Manage Role", "Index", "Role")</li>
    </h3>
}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) .We will add user module soon </h2>
}

WebApplication/Views/Users/Users.cshtml
@using WebApplication.Models

@{
    ViewBag.Title = "Users";
}

@section PageStyles {
    <link type="text/css" href="@Url.Content("~/Content/contacts.css")" rel="stylesheet" />
}

@Scripts.Render("~/Scripts/contacts.js")

<script type="text/x-kendo-tmpl" id="single-contact-template">
    <div class="contact-view k-widget" uid="#: uid #">
        <div class="header">
            <span class="hidden-email" style="display:none">#: Email #</span>
            <span class="image-wrapper">
                <img src="# if (sessionStorage.getItem(Id)) {#data:image/png;base64,#:sessionStorage.getItem(Id)# # } else {#@(Url.Content("Contacts/Picture/"))#:Id# # } #" alt="#:Id # image"/>
            </span>
            <span class="name">#: Name #</span>
            <div class="edit-buttons">
                <span class="k-button k-single-email-button" ><span class="icon i-mail"></span></span>
                <span class="k-button k-single-edit-button" ><span class="icon i-edit"></span></span>
                <span class="k-button k-single-delete-button" ><span class="icon i-delete"></span></span>
            </div>
        </div>
        <div class="details">
            <div class="column">
                <p><span class="label">UserName</span>#if (UserName) {# #: UserName # #}# &nbsp;</p>
                <p><span class="label">Role</span>#if (Role) {# #: Role # #}# &nbsp;</p>
            </div>
            <div class="column">
                <p>
                    <span class="label">Company</span>
                    <span>#if (Company) {# #: Company # #}# &nbsp;</span>
                </p>
                <p>
                    <span class="label">Phone</span>
                    <span>#if (Phone) {# #: Phone # #}# &nbsp;</span>
                </p>
            </div>
        </div>
    </div>
</script>

@Html.Partial("Sidebar")

<section class="main-section">
    <div class="toolbar">
        <div class="left">
            <span class="btn btn-export-pdf" onclick="exportPeople()">Export to PDF</span>
        </div>
        <div class="right">
            <span class="btn btn-vertical-pane iconOnly selected" onclick="changeToListDetails(this)" title="Display vertical panes"></span>
            <span class="btn btn-cards iconOnly" onclick="changeToContactsCards(this)" title="Display cards"></span>
        </div>
    </div>
    <div class="inner-section list-view">
        <div class="list-view-inner">
            <span class="searchbox">
                <input type="text" class="k-input search-textbox" placeholder="Search Users ...">
            </span>
            @(Html.Kendo().ListView<WebApplication.Models.ApplicationUser>()
                .Name("mainWidget")
                .TagName("div")
                .ClientTemplateId("single-contact-template")
                .DataSource(dataSource => dataSource
                    .Model(model => model.Id("Id"))
                    .Create(create => create.Action("Users_Create", "Users"))
                    .Read(read => read.Action("Users_Read", "Users"))
                    .Update(update => update.Action("Users_Update", "Users"))
                    .Destroy(destroy => destroy.Action("Users_Destroy", "Users"))
                )
                .Editable()
                .Selectable()
                .Events(e => e
                    .DataBound("onListViewDataBound")
                    .Change("onListViewSelectionChange")
                    .Edit("onListViewEdit")
                    .Cancel("onListViewChangeCancel")
                    .Save("onListViewChangeSave")
                )
                .HtmlAttributes(new { @class = "contacts-list" })
            )
        </div>
        <div class="single-contact-details k-widget">
        </div>
    </div>
</section>